server:
  port: 8081

spring:
  application:
    name: ChatTest
  thymeleaf:
    # 关闭thymeleaf缓存
    cache: false
  redis:
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码(如没有密码请注释掉)
    password: zhtj2024_cqyt.com
    # 连接超时时间
    timeout: 10s
    # 是否开启ssl
    ssl: false
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s

# 消息增强器配置
messageplus:
  persistence: true # 开启持久化
  service-id: 1001
