server:
  port: 8081

spring:
  application:
    name: message-plus-test
  thymeleaf:
    # 关闭thymeleaf缓存
    cache: false

# 消息增强器配置
messageplus:
  persistence: true # 开启持久化
#  service-id: 1001
  cluster:
    open: true # 开启集群
  message:
    expiration-time: 10 # 消息过期时间
    concurrent-number: 1
    message-persistence: true


