server:
  port: 8080

spring:
  application:
    name: ChatTest
  redis:
    host: 192.168.1.129
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s

# 消息增强器配置
messageplus:
  persistence: true # 开启持久化
